---
templateVersion: '2020-01-25'
componentName: aws.greengrass.secret.manager
description: AWS Greengrass Secret Manager
publisher: AWS
version: '0.0.0'
manifests:
  - platform:
      os: linux
    parameters:
      - name: cloudSecrets
        value: '[]'
        type: STRING
      - name: accessControl
        value: '[]'
        type: STRING
    artifacts:
      - uri: s3://gg-dev-artifacts/$componentName/$platform.os/$version/aws.greengrass.secret.manager.jar
