---
RecipeFormatVersion: '2020-01-25'
ComponentName: aws.greengrass.SecretManager
ComponentDescription: AWS Greengrass Secret Manager
ComponentPublisher: AWS
ComponentVersion: '0.0.0'
ComponentConfiguration:
  DefaultConfiguration:
    cloudSecrets: '[]'
Manifests:
  - Platform:
      os: linux
    Parameters:
      - Name: cloudSecrets
        Value: '[]'
        Type: STRING
    Artifacts:
      - URI: s3://gg-dev-artifacts-$stage/$componentName/$platform.os/$version/aws.greengrass.SecretManager.jar
